apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: database

resources:
  - postgresql-statefulset.yaml
  - postgresql-service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: postgres-config
    literals:
      - POSTGRES_DB=ad
      - POSTGRES_USER=test

secretGenerator:
  - name: postgres-secret
    literals:
      - POSTGRES_PASSWORD=test
